name = "ai-cms"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "cms-db"
database_id = "374d2c8f-5071-43f2-b95e-05315559a8b0"

[[r2_buckets]]
binding = "R2"
bucket_name = "cms-media"

[ai]
binding = "AI"

[vars]
NEXT_PUBLIC_SITE_URL = "https://ai-cms-bn5.pages.dev"
